# docker-compose.yml

version: "3.8"

services:
  yii2-app:
    image: yii2-app:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
